
# catch this error for input can input again 
x = int(input("input number :"))
print(x)